spring.application.name=kataecommerce

# ==================================================
# MongoDB
# ==================================================

spring.mongodb.database=kataecommerce
de.flapdoodle.mongodb.embedded.version=7.0.4

# ==================================================
# Web
# ==================================================

server.servlet.context-path=/api
server.port=8080